version: '3'

services:

  linebot:
    image: linebot:test
    ports:
      - "8080:8080"
    working_dir: /app
    networks:
      - mqtt
    command: ["python", main.py]

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # - ./mosquitto/data:/mosquitto/data
      # - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt
    restart: always

networks:
  mqtt:
    driver: bridge